# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

# FLYWAY
spring.flyway.clean-disabled=true

# LOGGING (dev ?????)
logging.level.org.springframework.web=${LOG_LEVEL_WEB:DEBUG}
logging.level.org.hibernate.SQL=${LOG_LEVEL_SQL:DEBUG}
logging.level.org.hibernate.orm.jdbc.bind=${LOG_LEVEL_BIND:TRACE}
logging.level.com.ms.executionservice=${LOG_LEVEL_APP:DEBUG}

# OPENAPI (???????)
springdoc.api-docs.enabled=${OPENAPI_ENABLED:true}
springdoc.swagger-ui.enabled=${SWAGGER_UI_ENABLED:true}

# SERVICES
flowact.services.workflow.base-url=${WORKFLOW_SERVICE_URL}
flowact.services.ml.base-url=${ML_SERVICE_URL}
flowact.services.gateway.base-url=${GATEWAY_SERVICE_URL}
