# ======================
# JPA
# ======================
spring.jpa.show-sql=${JPA_SHOW_SQL:true}

# ======================
# FLYWAY
# ======================
spring.flyway.clean-disabled=true
spring.flyway.locations=classpath:db/migration,classpath:db/testdata

# ======================
# SQL INIT
# ======================
# Schema and init data are managed by Flyway in init profile.
# Do not enable spring.sql.init together with Flyway here: it can create
# a circular dependency between flyway and entityManagerFactory.
spring.sql.init.mode=never

# ======================
# LOGGING
# ======================
logging.level.org.springframework.web=${LOG_LEVEL_WEB:DEBUG}
logging.level.org.hibernate.SQL=${LOG_LEVEL_SQL:DEBUG}
logging.level.org.hibernate.orm.jdbc.bind=${LOG_LEVEL_BIND:TRACE}
logging.level.com.ms.executionservice=${LOG_LEVEL_APP:DEBUG}

# ======================
# OPENAPI
# ======================
springdoc.api-docs.enabled=${OPENAPI_ENABLED:true}
springdoc.swagger-ui.enabled=${SWAGGER_UI_ENABLED:true}
