# ======================
# JPA
# ======================
spring.jpa.show-sql=false

# ======================
# FLYWAY
# ======================
spring.flyway.clean-disabled=true

# ======================
# SQL INIT
# ======================
spring.sql.init.mode=never

# ======================
# OPENAPI
# ======================
springdoc.api-docs.enabled=${OPENAPI_ENABLED:false}
springdoc.swagger-ui.enabled=${SWAGGER_UI_ENABLED:false}

# ======================
# ACTUATOR
# ======================
management.endpoint.health.show-details=${HEALTH_DETAILS:never}

# ======================
# LOGGING
# ======================
logging.level.root=${LOG_LEVEL_ROOT:INFO}
logging.level.org.springframework.web=${LOG_LEVEL_WEB:WARN}
logging.level.org.hibernate.SQL=${LOG_LEVEL_SQL:WARN}
logging.level.org.hibernate.orm.jdbc.bind=${LOG_LEVEL_BIND:WARN}
logging.level.com.ms.executionservice=${LOG_LEVEL_APP:INFO}
