apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.yaml
  - databases.yaml
  - kafka.yaml
  - apps.yaml
  - ingress.yaml

images:
  - name: ghcr.io/michail19/flowact-user-service
    newTag: review

  - name: ghcr.io/michail19/flowact-execution-service
    newTag: review

  - name: ghcr.io/michail19/flowact-worker-service
    newTag: review

  - name: ghcr.io/michail19/flowact-ml-service
    newTag: review

  - name: ghcr.io/michail19/flowact-frontend
    newTag: review
